--
-- PostgreSQL database dump
--

\restrict TaU0IeiaM7oekPckufqnJB39FOdpgHBkvL1eb8Ba5ZdZSF4YjkyV3aKHQCdc7eB

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.0

-- Started on 2026-09-03 10:01:52

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 229 (class 1259 OID 52436)
-- Name: Admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Admins" (
    "Id" integer NOT NULL,
    "Email" character varying(200) NOT NULL,
    "PasswordHash" text NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Role" integer DEFAULT 0 NOT NULL,
    "IsDeleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Admins" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 52435)
-- Name: Admins_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Admins" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Admins_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 52288)
-- Name: Customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Customers" (
    "Id" integer CONSTRAINT "Users_Id_not_null" NOT NULL,
    "FullName" character varying(200) CONSTRAINT "Users_FullName_not_null" NOT NULL,
    "Address" character varying(300) CONSTRAINT "Users_Address_not_null" NOT NULL,
    "PhoneNumber" character varying(30) CONSTRAINT "Users_PhoneNumber_not_null" NOT NULL,
    "ApiKey" character varying(100) CONSTRAINT "Users_ApiKey_not_null" NOT NULL,
    "CreatedAt" timestamp with time zone CONSTRAINT "Users_CreatedAt_not_null" NOT NULL,
    "IsDeleted" boolean DEFAULT false CONSTRAINT "Users_IsDeleted_not_null" NOT NULL
);


ALTER TABLE public."Customers" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 52302)
-- Name: Meters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Meters" (
    "Id" integer NOT NULL,
    "MeterSerialNumber" character varying(13) NOT NULL,
    "UserId" integer NOT NULL,
    "IsDeleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Meters" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 52301)
-- Name: Meters_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Meters" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Meters_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 52277)
-- Name: ProcessingFees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProcessingFees" (
    "Id" integer NOT NULL,
    "FixedAmount" numeric(18,5) NOT NULL,
    "PercentageRate" numeric(18,5) NOT NULL,
    "IsDeleted" boolean CONSTRAINT "ProcessingFees_IsActive_not_null" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."ProcessingFees" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 52276)
-- Name: ProcessingFees_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProcessingFees" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProcessingFees_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 52316)
-- Name: Transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Transactions" (
    "Id" integer NOT NULL,
    "MeterId" integer NOT NULL,
    "Amount" numeric(18,5) NOT NULL,
    "ProcessingFeeAmount" numeric(18,5) NOT NULL,
    "EnergyAmount" numeric(18,5) NOT NULL,
    "Token" text,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "PublicId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);


ALTER TABLE public."Transactions" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 52315)
-- Name: Transactions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Transactions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transactions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 52287)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Customers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 52269)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4960 (class 0 OID 52436)
-- Dependencies: 229
-- Data for Name: Admins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Admins" ("Id", "Email", "PasswordHash", "FullName", "CreatedAt", "Role", "IsDeleted") FROM stdin;
4	minaadmin@gmail.com	$2a$11$.jjqJz7wQicUz/GCYqSiMe7m7AwqI1jgRBu2bMNEDsZfxxwZOAj0K	Mina aaa	2026-08-26 12:52:04.11767+00	0	f
3	admin1@gmail.com	$2a$11$3R2eFRTNR/OskrknrsWiWOuVQRGxts8GhLyr8tzpJaH1.MZWHvwx6	Novi adminn	2026-08-26 12:49:51.49977+00	0	t
7	admin1@gmail.com	$2a$11$kInDV2D3UKOnfOI5SCpwHuWKkOyaSed/vp0YXaa50ruHjU6SG0d4q	asda	2026-08-27 07:49:30.960173+00	0	f
1	admin@vending.com	$2a$11$x.aSskr3ChMXM7OZMcZ2OeY5HJi4ZDhAoj8dtkGu6xGgnsOzFQd4a	Super Admin	2026-08-25 10:48:16.576798+00	1	f
2	obicni.admin@vending.com	$2a$11$x7kJkDh7NpfokziV6v8D0uaJocrwE5Bwo3MZTByonYXAQfBOJo51.	Novo ime	2026-08-25 13:58:27.695697+00	0	f
8	noviadmin1@gmail.com	$2a$11$3p/6Kf8O9c.1.bSp8/S8s.g31KjsNMoSftvWcyYLE5hCjK1pToxzq	noviAdmin1	2026-09-01 12:51:32.985252+00	0	f
9	noviadmin2@gmail.com	$2a$11$y5vusSO71INeKNtaDiFoledT5guZdSmUwj62MNcL4bWiFgF63Uicm	noviAdmin2	2026-09-01 12:51:57.850963+00	0	f
10	noviadmin3@gmail.com	$2a$11$TBPva2jui74OYIyl8pAWruW4T7A2J42rXT6XXjWtv.A/K0a/FPgxa	noviAdmin3	2026-09-01 12:52:20.63246+00	0	f
11	noviadmin4@gmail.com	$2a$11$ZLpPlk7CKKPJqb9drNd1cOXLSMbkzgT8342skpbjUDih9TdB4Elva	noviAdmin4	2026-09-01 12:52:44.632667+00	0	f
12	noviadmin5@gmail.com	$2a$11$jBlBMXx3fSC2W7VT91llrOmygamevFx0VZrQWvo04Rla3PKxoiMR6	noviAdmin5	2026-09-01 12:53:18.719172+00	0	f
15	noviadmin8@gmail.com	$2a$11$C/pxoCJbCN73U701ma6Bmex1i4K2/XM5RMGNzi3/v4aeYLQXMh5je	noviAdmin8	2026-09-01 12:54:49.67257+00	0	f
14	noviadmin7@gmail.com	$2a$11$B1d23Br3RMT4G8wGUU0AwutT7gb/AuhSChYlZTJiYFPoTc1ZJVyvu	noviAdmin7	2026-09-01 12:54:11.92619+00	0	f
13	noviadmin6@gmail.com	$2a$11$dZApAz3fDt.yPmjeHloQPeF0kZ7HVhjEvJL5rsu.BsBI6GnMTvy9O	noviAdmin6	2026-09-01 12:53:43.582467+00	0	f
16	noviadmin9@gmail.com	$2a$11$Og7GFzi9sjLyLQmEHSvQ9.YZAePBUR8xI4Qizkif8EXnEj.z6Nwqq	noviAdmin9	2026-09-01 12:56:26.422183+00	0	f
17	noviadmin10@gmail.com	$2a$11$.hE5NBEofuPtw1imFpcmXekTWlW13DxV0xQXIA3VUbzWr66iYWXSa	noviAdmin10	2026-09-01 12:56:51.154891+00	0	f
\.


--
-- TOC entry 4954 (class 0 OID 52288)
-- Dependencies: 223
-- Data for Name: Customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Customers" ("Id", "FullName", "Address", "PhoneNumber", "ApiKey", "CreatedAt", "IsDeleted") FROM stdin;
13	Teodora Aleksić	Bulevar despota Stefana	0601234567	dfa971e1-07f5-4bb1-98fc-3970f6cf1d5e	2026-08-20 09:32:04.712021+00	f
17	Petar Petrović	Test ulica 10	0641234567	6f4fe3a9-0527-4a67-a1b8-00ee31949383	2026-08-20 10:13:26.755318+00	f
19	Petar Petrović	Test ulica 10	0641234567	71fd1eb5-abf9-4854-9760-d3b7003f805e	2026-08-20 10:15:06.648801+00	f
22	Test User 1	Test Address 1	0600000001	1bdb695e-5ea9-4bb6-af24-d0e158412152	2026-08-20 11:55:18.64108+00	f
23	Test User 2	Test Address 2	0600000002	aa1bb8b4-ad7f-4998-bf70-027803053ffd	2026-08-20 11:55:18.64108+00	f
24	Test User 3	Test Address 3	0600000003	b48ea71a-c03e-4b44-9863-20ef77085cef	2026-08-20 11:55:18.64108+00	f
25	Test User 4	Test Address 4	0600000004	6a5f4705-6af5-4640-80b7-0926e7a970da	2026-08-20 11:55:18.64108+00	f
26	Test User 5	Test Address 5	0600000005	2001b17f-d628-4b00-90ef-1b73355d51eb	2026-08-20 11:55:18.64108+00	f
27	Test User 6	Test Address 6	0600000006	ca893ace-d3b1-43f8-8a72-a9038bf7f8b3	2026-08-20 11:55:18.64108+00	f
28	Test User 7	Test Address 7	0600000007	acb524c0-e872-41d1-ab7a-b90bfac6e1b7	2026-08-20 11:55:18.64108+00	f
29	Test User 8	Test Address 8	0600000008	8a05e1a0-d329-4d8d-9f07-3de0d0cf452e	2026-08-20 11:55:18.64108+00	f
30	Test User 9	Test Address 9	0600000009	ac027ae7-65a3-4980-8ae5-5f36effbd914	2026-08-20 11:55:18.64108+00	f
31	Test User 10	Test Address 10	0600000010	323f9bd2-fb50-4f25-86b5-024fa8371535	2026-08-20 11:55:18.64108+00	f
32	Test User 11	Test Address 11	0600000011	a004d216-0929-442e-8afe-1aa2d758740b	2026-08-20 11:55:18.64108+00	f
33	Test User 12	Test Address 12	0600000012	0bfd3517-1ab2-49a0-8985-13755b9dfc6f	2026-08-20 11:55:18.64108+00	f
34	Test User 13	Test Address 13	0600000013	bd7e3470-b244-4a0a-8091-e3d06ca077a4	2026-08-20 11:55:18.64108+00	f
35	Test User 14	Test Address 14	0600000014	3db12292-6882-4592-b54b-f858a4e80424	2026-08-20 11:55:18.64108+00	f
36	Test User 15	Test Address 15	0600000015	cadaaf9b-8086-4db1-8ddf-64c967af0915	2026-08-20 11:55:18.64108+00	f
37	Test User 16	Test Address 16	0600000016	f68533ca-07f8-4fd0-aa54-fbe5f52214bd	2026-08-20 11:55:18.64108+00	f
38	Test User 17	Test Address 17	0600000017	db39bbd2-c5a4-4c73-8955-b41445cb16fc	2026-08-20 11:55:18.64108+00	f
39	Test User 18	Test Address 18	0600000018	4888fe6f-4dc6-42d5-ad7e-8a3a2bb5ae48	2026-08-20 11:55:18.64108+00	f
40	Test User 19	Test Address 19	0600000019	ee0d617a-766d-4384-8e05-50ed4499b05d	2026-08-20 11:55:18.64108+00	f
41	Test User 20	Test Address 20	0600000020	b89f4800-2a05-4b05-9c6b-d8719c9f721f	2026-08-20 11:55:18.64108+00	f
42	Test User 21	Test Address 21	0600000021	4629a755-9488-41ed-b325-fd1828e4c70e	2026-08-20 11:55:18.64108+00	f
43	Test User 22	Test Address 22	0600000022	265809fa-ae59-47e3-be38-7ce959b8292b	2026-08-20 11:55:18.64108+00	f
44	Test User 23	Test Address 23	0600000023	a634ed18-3386-40a7-9877-53b5b57e9aba	2026-08-20 11:55:18.64108+00	f
45	Test User 24	Test Address 24	0600000024	552fa307-4523-4e6b-ab7b-619598d7019d	2026-08-20 11:55:18.64108+00	f
46	Test User 25	Test Address 25	0600000025	e8ac3e04-3f32-4a50-a951-d431b0d57fe4	2026-08-20 11:55:18.64108+00	f
4	Ana Anic	neka ulica	0601234567	4865516c-d1ac-4dc4-b10c-de475698ca4a	2026-08-20 08:54:55.894405+00	f
1	Marko Markovic	Zmaj Jovina 12, Novi Sad	0601234568	ca2000b8-2b67-4aef-ab8d-5581d7edde69	2026-08-19 14:11:33.492625+00	t
56	Test Bez Brojila	Test	0640000000	664987e7-d816-46b1-a975-7c6855e1c70e	2026-08-25 10:24:21.407689+00	f
\.


--
-- TOC entry 4956 (class 0 OID 52302)
-- Dependencies: 225
-- Data for Name: Meters; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Meters" ("Id", "MeterSerialNumber", "UserId", "IsDeleted") FROM stdin;
13	00000000008	13	f
17	00000000099	17	f
19	00000000096	19	f
22	00100000001	22	f
23	00100000002	23	f
24	00100000003	24	f
25	00100000004	25	f
26	00100000005	26	f
27	00100000006	27	f
28	00100000007	28	f
29	00100000008	29	f
30	00100000009	30	f
31	00100000010	31	f
32	00100000011	32	f
33	00100000012	33	f
34	00100000013	34	f
35	00100000014	35	f
36	00100000015	36	f
37	00100000016	37	f
38	00100000017	38	f
39	00100000018	39	f
40	00100000019	40	f
41	00100000020	41	f
42	00100000021	42	f
43	00100000022	43	f
44	00100000023	44	f
45	00100000024	45	f
46	00100000025	46	f
4	00000000070	4	f
1	00000000001	1	t
61	00000000001	56	f
\.


--
-- TOC entry 4952 (class 0 OID 52277)
-- Dependencies: 221
-- Data for Name: ProcessingFees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProcessingFees" ("Id", "FixedAmount", "PercentageRate", "IsDeleted", "CreatedAt") FROM stdin;
1	10.00000	0.02000	t	2026-08-19 14:07:43.844799+00
2	15.00000	0.03000	t	2026-08-20 09:15:24.648794+00
3	15.00000	0.03000	t	2026-08-20 10:17:45.867373+00
4	5.00000	0.70000	t	2026-08-26 13:49:13.9951+00
5	80.00000	0.75000	t	2026-08-26 14:15:30.292454+00
6	95.00000	0.80000	t	2026-08-28 09:54:05.502176+00
7	1000.00000	0.30000	t	2026-08-28 09:57:29.477531+00
8	25.00000	0.05000	f	2026-08-28 10:01:49.547911+00
\.


--
-- TOC entry 4958 (class 0 OID 52316)
-- Dependencies: 227
-- Data for Name: Transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Transactions" ("Id", "MeterId", "Amount", "ProcessingFeeAmount", "EnergyAmount", "Token", "Status", "CreatedAt", "IsDeleted", "PublicId") FROM stdin;
1	1	1000.00000	30.00000	970.00000	\N	2	2026-08-19 14:13:52.513517+00	f	56a01c86-a04d-428d-88aa-e1a15779b745
2	1	1000.00000	30.00000	970.00000	\N	2	2026-08-19 14:14:16.673553+00	f	f2385f36-2c6b-4beb-a4f8-3a55b869ae68
3	1	1000.00000	30.00000	970.00000	91439031569432552785	1	2026-08-19 14:16:37.048961+00	f	e0d4512e-b225-4f70-b138-fafa213dcb7b
4	1	1000.00000	30.00000	970.00000	61082978019441164063	1	2026-08-20 09:14:51.886917+00	f	3c4dbf3b-1808-4822-927d-79b103c1fbff
5	1	1000.00000	45.00000	955.00000	46545989793735451827	1	2026-08-20 10:19:14.072386+00	f	0cc884c4-e011-46d4-8885-1c617b6927bc
6	1	1000.00000	45.00000	955.00000	24300243243157276487	1	2026-08-21 08:39:23.821768+00	f	2e848007-846c-4590-9361-046bde496b19
7	13	1000.00000	75.00000	925.00000	92873864900201959032	1	2026-08-31 09:10:59.589262+00	f	d346f215-2caa-48b1-b49b-d102504c55d0
8	13	1000.00000	75.00000	925.00000	\N	2	2026-08-31 10:02:24.006285+00	f	026778e7-3670-4a1a-8fc7-f9e40e06506f
9	13	1000.00000	75.00000	925.00000	29316064989719467556	1	2026-08-31 10:33:53.753108+00	f	f617dc64-e28f-49be-aee4-646fccbb63bd
10	13	1000.00000	75.00000	925.00000	58961917105091740916	1	2026-08-31 10:38:35.866569+00	f	90521fc1-9b37-4a6d-b9ab-8240a2f8358e
11	13	1000.00000	75.00000	925.00000	16105220137035524426	1	2026-08-31 10:48:53.201558+00	f	33446f66-847b-4633-adcf-e506ce1bfce0
12	13	1000.00000	75.00000	925.00000	19025959147487840429	1	2026-08-31 11:44:31.751257+00	f	64649c2b-af96-4d51-9c84-02789157e44e
13	13	1000.00000	75.00000	925.00000	20820243436651380439	1	2026-09-01 07:54:15.258428+00	f	6b74442a-aa1d-4a58-9b4c-0569c44eedd4
14	13	1000.00000	75.00000	925.00000	14422450189502443831	1	2026-09-01 08:13:21.625166+00	f	dd5aacc8-9080-476f-be2a-e2c12edcc6aa
15	13	1000.00000	75.00000	925.00000	13214448178412350139	1	2026-09-01 08:26:24.94851+00	f	b8306d63-a502-408b-80b1-86ab652c03a6
16	13	1000.00000	75.00000	925.00000	24064919759196518281	1	2026-09-01 08:30:05.448883+00	f	2c7a74d8-c600-4941-b51d-ea6e417841e9
17	13	1000.00000	75.00000	925.00000	70750805800532400517	1	2026-09-01 09:45:08.288213+00	f	582d79cf-e9da-4ecf-97b5-98fb26b524c0
18	13	1000.00000	75.00000	925.00000	11194089559669542860	1	2026-09-01 09:45:08.286252+00	f	82c03d91-7499-4a2c-908e-d5cae52b3200
19	13	1000.00000	75.00000	925.00000	18391768114202997078	1	2026-09-01 09:45:37.336724+00	f	5c4e085a-7f84-4b85-957e-164d531a0da1
20	13	1000.00000	75.00000	925.00000	87380382993057973692	1	2026-09-01 10:28:48.052406+00	f	c216d166-b475-446c-9c84-f18a10e8a45e
21	13	1000.00000	75.00000	925.00000	92787352354919273333	1	2026-09-01 10:30:22.085884+00	f	673a44f9-83f0-47fa-839c-86e6ea0e3f9c
22	13	1000.00000	75.00000	925.00000	13248890124032889350	1	2026-09-01 10:40:39.20419+00	f	d3160b76-bd97-4943-aae8-e2a8233ed362
23	13	1000.00000	75.00000	925.00000	99948878832886595552	1	2026-09-01 10:44:31.769026+00	f	db80343d-000f-4cef-abf3-880d16eb4389
24	13	1000.00000	75.00000	925.00000	56961243866309317428	1	2026-09-01 10:44:58.777587+00	f	584af6f3-614c-4512-a511-6cbf7efa27d6
25	13	1000.00000	75.00000	925.00000	46798944505341705785	1	2026-09-01 10:51:24.256533+00	f	ada45d9c-5727-449b-b55c-4ec0a6b35a74
26	13	1000.00000	75.00000	925.00000	68518591019465125758	1	2026-09-01 11:14:31.834305+00	f	1a97ea13-4411-40a1-8032-9e449a4d4df0
27	13	1000.00000	75.00000	925.00000	27714934840389664471	1	2026-09-01 11:35:37.698326+00	f	4e4155c8-63db-4166-8214-38f139d05949
\.


--
-- TOC entry 4950 (class 0 OID 52269)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260819140404_InitialCreate	8.0.11
20260821104631_RenameProcessingFeeIsActiveToIsDeleted	8.0.11
20260821111002_AddIsDeletedToAllEntities	8.0.11
20260821114238_MakeMeterSerialNumberUniqueOnlyForActive	8.0.11
20260821122425_RenameUserToCustomer	8.0.11
20260825083936_AddAdminEntity	8.0.11
20260826080525_ChangeAdminIsSuperAdminToRole	8.0.11
20260827072912_AddIsDeletedToAdmin	8.0.11
20260901110533_AddPublicIdToTransaction	8.0.11
\.


--
-- TOC entry 4966 (class 0 OID 0)
-- Dependencies: 228
-- Name: Admins_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Admins_Id_seq"', 17, true);


--
-- TOC entry 4967 (class 0 OID 0)
-- Dependencies: 224
-- Name: Meters_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Meters_Id_seq"', 61, true);


--
-- TOC entry 4968 (class 0 OID 0)
-- Dependencies: 220
-- Name: ProcessingFees_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProcessingFees_Id_seq"', 8, true);


--
-- TOC entry 4969 (class 0 OID 0)
-- Dependencies: 226
-- Name: Transactions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Transactions_Id_seq"', 27, true);


--
-- TOC entry 4970 (class 0 OID 0)
-- Dependencies: 222
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 56, true);


--
-- TOC entry 4800 (class 2606 OID 52448)
-- Name: Admins PK_Admins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Admins"
    ADD CONSTRAINT "PK_Admins" PRIMARY KEY ("Id");


--
-- TOC entry 4795 (class 2606 OID 52309)
-- Name: Meters PK_Meters; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Meters"
    ADD CONSTRAINT "PK_Meters" PRIMARY KEY ("Id");


--
-- TOC entry 4788 (class 2606 OID 52286)
-- Name: ProcessingFees PK_ProcessingFees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProcessingFees"
    ADD CONSTRAINT "PK_ProcessingFees" PRIMARY KEY ("Id");


--
-- TOC entry 4798 (class 2606 OID 52329)
-- Name: Transactions PK_Transactions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id");


--
-- TOC entry 4791 (class 2606 OID 52300)
-- Name: Customers PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4786 (class 2606 OID 52275)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4789 (class 1259 OID 52338)
-- Name: IX_Customers_ApiKey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Customers_ApiKey" ON public."Customers" USING btree ("ApiKey");


--
-- TOC entry 4792 (class 1259 OID 52429)
-- Name: IX_Meters_MeterSerialNumber; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Meters_MeterSerialNumber" ON public."Meters" USING btree ("MeterSerialNumber") WHERE ("IsDeleted" = false);


--
-- TOC entry 4793 (class 1259 OID 52336)
-- Name: IX_Meters_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Meters_UserId" ON public."Meters" USING btree ("UserId");


--
-- TOC entry 4796 (class 1259 OID 52337)
-- Name: IX_Transactions_MeterId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transactions_MeterId" ON public."Transactions" USING btree ("MeterId");


--
-- TOC entry 4801 (class 2606 OID 52430)
-- Name: Meters FK_Meters_Customers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Meters"
    ADD CONSTRAINT "FK_Meters_Customers_UserId" FOREIGN KEY ("UserId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4802 (class 2606 OID 52330)
-- Name: Transactions FK_Transactions_Meters_MeterId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "FK_Transactions_Meters_MeterId" FOREIGN KEY ("MeterId") REFERENCES public."Meters"("Id") ON DELETE CASCADE;


-- Completed on 2026-09-03 10:01:53

--
-- PostgreSQL database dump complete
--

\unrestrict TaU0IeiaM7oekPckufqnJB39FOdpgHBkvL1eb8Ba5ZdZSF4YjkyV3aKHQCdc7eB

